// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlzinzhtghlinqmrsodb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsemluemh0Z2hsaW5xbXJzb2RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwMjU5NjIsImV4cCI6MjA3NjYwMTk2Mn0.XpZghm1Bq9hGn_Qyu-R-K2xMV3aXju7NGQ-91s5gQK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});